{"name": "test_post_json", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'url'", "trace": "@pytest.fixture(scope='session')\n    def pub_data():\n>       data = {'token':login('')}\n\nH:\\项目\\api_test\\conftest.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nH:\\项目\\api_test\\conftest.py:20: in login\n    r = request_tool.request(method=method, url=uri, pub_data=pub_data, json_data=json_data, status_code=status_code,\ntools\\report\\decorators_tool.py:102: in function\n    resp = func(*args,**kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nargs = ()\nkwargs = {'json': {'password': 'admin123', 'username': 'admin'}, 'method': 'POST', 'url': 'http://192.168.50.58:81/userapi/login'}\nr = ()\n\n    def _func(*args, **kwargs):\n        r= func(*args, **kwargs)\n        request = \"-------------------request-------------\" \\\n>                 \"\\n{0}\\n{1}\\n{2}\".format(r.url, string_tool.dic_to_str(r.request.headers), r.request.body)\nE       AttributeError: 'tuple' object has no attribute 'url'\n\ntools\\report\\decorators_tool.py:15: AttributeError"}, "attachments": [{"name": "log", "source": "482146c4-9dbd-4635-9f17-7e7e4a19b76c-attachment.txt", "type": "text/plain"}], "start": 1619063015868, "stop": 1619063015868, "uuid": "796cfc88-5e4a-4081-926b-83b15f7b1560", "historyId": "f07f20f711a3d783b17eac6fedd1a4b3", "fullName": "test_case.test_ure#test_post_json", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_ure"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-1DBKS4O"}, {"name": "thread", "value": "31332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_ure"}]}