ERROR    tools.report.log_tool:log_tool.py:46 Exception url: http://192.168.50.58:81/userapi/login
ERROR    tools.report.log_tool:log_tool.py:46 HTTPConnectionPool(host='192.168.50.58', port=81): Max retries exceeded with url: /userapi/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E06F5C2070>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))